language: java

jdk:
  - openjdk8

install: true

branches:
  only:
    - master

services:
  - xvfb

before_install: ./tool/bootstrap.sh

before_script:
  - git clone --depth 1 https://github.com/flutter/flutter.git ../flutter
  - export PATH="$PATH":`pwd`/../flutter/bin:`pwd`/../flutter/bin/cache/dart-sdk/bin
  - flutter config --no-analytics
  - flutter doctor
  - export FLUTTER_SDK=`pwd`/../flutter

# execution
script: ./tool/travis.sh

# Testing product matrix; env values are appended to from product-matrix.json.
matrix:
  include:
    - os: windows
      env: UNIT_TEST_BOT=true
      language: shell

env:
  - DART_BOT=true
  - CHECK_BOT=true
  - UNIT_TEST_BOT=true
